#!/usr/bin/env python3
"""Precomputes additive/subtractive palette-mixing geometry for every
palette in palettize.PALETTES and writes it to palette_data.js as a
static data module.

Run this once at "build" time -- whenever a palette is added, removed,
or changed in palettize.py -- not live in the browser. The demo used to
compute this in-browser on demand via Pyodide (real CPython + numpy
compiled to WASM, running export_hull_uniforms.py's / export_km_uniforms
.py's own build_uniforms() unmodified): that made any palette added to
PALETTES work with no web-specific step, but paid a multi-second
Pyodide+numpy CDN fetch on every page load and a fresh compute on every
palette switch, for a palette *set* that in practice is fixed and known
ahead of time. This script keeps the same single source of truth
(build_uniforms(), unchanged) but runs it once, offline, with the real
CPython/numpy already installed for the CLI -- palette_data.js then
ships the numbers directly, and palettize.js precompiles one shader
program per palette at page load (see AdditivePipeline/
SubtractivePipeline.prewarmAll()) instead of recompiling on switch.

Usage:
    python3 build_palette_data.py
"""
import json
import os
import sys

_WEB_DIR = os.path.dirname(os.path.abspath(__file__))
_WALLPAPER_DIR = os.path.dirname(_WEB_DIR)
_SHADERS_DIR = os.path.dirname(_WALLPAPER_DIR)
_REPO_ROOT = os.path.dirname(_SHADERS_DIR)
sys.path.insert(0, _SHADERS_DIR)
sys.path.insert(0, _REPO_ROOT)

import numpy as np
import palettize as nf
import export_hull_uniforms
import export_km_uniforms


def _tolist(d):
    return {k: (v.tolist() if isinstance(v, np.ndarray) else v) for k, v in d.items()}


def main():
    geometry = {}
    for name in sorted(nf.PALETTES):
        geometry[name] = {
            'additive': _tolist(export_hull_uniforms.build_uniforms(name)),
            'subtractive': _tolist(export_km_uniforms.build_uniforms(name)),
        }

    dst = os.path.join(_WEB_DIR, 'palette_data.js')
    with open(dst, 'w') as f:
        f.write('// GENERATED by build_palette_data.py -- do not hand-edit.\n')
        f.write('// Regenerate with `python3 build_palette_data.py` whenever palettize.PALETTES changes.\n')
        f.write('export const PALETTE_GEOMETRY = ')
        f.write(json.dumps(geometry))
        f.write(';\n')
    print(f'wrote {dst} ({len(geometry)} palettes: {", ".join(sorted(geometry))})')


if __name__ == '__main__':
    main()
