#!/usr/bin/env python3
"""Generates shaders.js from the canonical GLSL sources in shaders/,
shaders/wallpaper/, and shaders/night/ -- the single source of truth is
the .frag/.vert/.glsl files; this script is the only place that knows
how to turn them into browser-ready GLSL ES 300 strings, so there is
exactly one transformation to keep correct rather than ~35 hand-
transcribed copies.

Two mechanical changes, applied to every file:
  1. `#version 330 core` -> `#version 300 es` + explicit precision
     qualifiers (GLSL ES requires them; desktop GLSL doesn't need them
     so the source files don't have them).
  2. common.glsl's contents are injected right after the `#version`
     line (same as pipeline.py's `_inject_common`) -- done here at
     build time rather than at runtime in JS, so the browser just gets
     complete, ready-to-compile strings with no assembly step.

Run this whenever a .frag/.vert/.glsl source changes:
    python3 build_shaders.py
"""
import json
import os

_WEB_DIR = os.path.dirname(os.path.abspath(__file__))
_WALLPAPER_DIR = os.path.dirname(_WEB_DIR)
_SHADERS_DIR = os.path.dirname(_WALLPAPER_DIR)
_NIGHT_DIR = os.path.join(_SHADERS_DIR, 'night')

ES_HEADER = "#version 300 es\nprecision highp float;\nprecision highp int;\nprecision highp sampler2D;\n"


def _read(path):
    with open(path) as f:
        return f.read()


def to_es300(src, common_src=None):
    assert src.startswith('#version 330 core'), 'expected a #version 330 core source'
    nl = src.index('\n')
    body = src[nl + 1:]
    if common_src is not None:
        body = common_src + '\n' + body
    return ES_HEADER + body


def _js_key(filename):
    return os.path.splitext(filename)[0].replace('.', '_') + ('_vert' if filename.endswith('.vert') else '_frag')


def collect(dir_path, common_src=None, only=None):
    """Returns {js_key: es300_source} for every .frag/.vert in dir_path
    (excluding .glsl includes and this script's own directory)."""
    out = {}
    for fn in sorted(os.listdir(dir_path)):
        if not (fn.endswith('.frag') or fn.endswith('.vert')):
            continue
        if only is not None and fn not in only:
            continue
        src = _read(os.path.join(dir_path, fn))
        out[_js_key(fn)] = to_es300(src, common_src)
    return out


def main():
    fullscreen_vert = to_es300(_read(os.path.join(_SHADERS_DIR, 'fullscreen.vert')))

    wallpaper_common = _read(os.path.join(_WALLPAPER_DIR, 'common.glsl'))
    wallpaper = collect(_WALLPAPER_DIR, wallpaper_common)

    night_common = _read(os.path.join(_NIGHT_DIR, 'common.glsl'))
    night = collect(_NIGHT_DIR, night_common)

    mixing = collect(_SHADERS_DIR, common_src=None, only={
        'additive_mix.frag', 'subtractive_mix.frag',
    })

    def emit_obj(name, d):
        lines = [f'export const {name} = {{']
        for k, v in sorted(d.items()):
            lines.append(f'  {k}: {_js_template_literal(v)},')
        lines.append('};')
        return '\n'.join(lines)

    out = []
    out.append('// GENERATED by build_shaders.py -- do not hand-edit.')
    out.append('// Regenerate with `python3 build_shaders.py` whenever a .frag/.vert/.glsl')
    out.append('// source under shaders/, shaders/wallpaper/, or shaders/night/ changes.')
    out.append('')
    out.append(f'export const FULLSCREEN_VERT = {_js_template_literal(fullscreen_vert)};')
    out.append('')
    out.append(emit_obj('WALLPAPER', wallpaper))
    out.append('')
    out.append(emit_obj('NIGHT', night))
    out.append('')
    out.append(emit_obj('MIXING', mixing))
    out.append('')

    dst = os.path.join(_WEB_DIR, 'shaders.js')
    with open(dst, 'w') as f:
        f.write('\n'.join(out))
    print(f"wrote {dst} ({len(wallpaper)} wallpaper + {len(night)} night + {len(mixing)} mixing shaders)")


def _js_template_literal(src):
    # The GLSL sources use backticks freely in their own comments (this
    # repo's comment style quotes identifiers in backticks), so a plain
    # backtick template literal isn't safe -- JSON string encoding
    # handles arbitrary content (backticks, quotes, backslashes)
    # correctly, and JSON string syntax is valid JS string syntax.
    return json.dumps(src)


if __name__ == '__main__':
    main()
